In [3]:
import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np

from src.config import SATHEALTH_DATA_DIR, RAW_DATA_DIR, COUNTY_DATA_DIR

In [4]:
airquality = pd.read_csv( COUNTY_DATA_DIR / 'airquality.csv')
airquality.head()

,COUNTYFP,year,month,total_aerosol_optical_depth_at_550nm_surface,particulate_matter_d_less_than_25_um_surface,NO2_column_number_density,ozone
0,1,2016,1,NaN,NaN,NaN,323.208001
1,1,2016,2,NaN,NaN,NaN,356.860486
2,1,2016,3,NaN,NaN,NaN,332.589376
3,1,2016,4,NaN,NaN,NaN,337.446316
4,1,2016,5,NaN,NaN,NaN,350.506551

In [5]:
climate = pd.read_csv( COUNTY_DATA_DIR / 'climate.csv')
climate.head()

,COUNTYFP,year,month,dewpoint_temperature_2m,temperature_2m,soil_temperature_level_1,soil_temperature_level_3,lake_bottom_temperature,lake_mix_layer_depth,lake_mix_layer_temperature,...,surface_thermal_radiation_downwards_sum,evaporation_from_bare_soil_sum,evaporation_from_the_top_of_canopy_sum,evaporation_from_open_water_surfaces_excluding_oceans_sum,total_evaporation_sum,u_component_of_wind_10m,v_component_of_wind_10m,surface_pressure,total_precipitation_sum,surface_runoff_sum
0,1,2016,1,265.809779,272.191800,273.777254,278.618110,274.626052,6.913982,274.521172,...,6.684055e+08,-0.005191,-0.002420,-0.002656,-0.014871,1.109925,0.475126,98676.667609,0.042839,0.000810
1,1,2016,2,269.880511,275.427578,275.779540,276.860096,274.600529,8.128015,274.575800,...,6.807634e+08,-0.010432,-0.007079,-0.003953,-0.024876,1.192782,0.396486,98552.734185,0.138204,0.017986
2,1,2016,3,276.725622,282.880216,282.673310,280.923999,279.385608,10.223921,279.376683,...,8.142498e+08,-0.031557,-0.011955,-0.009514,-0.054091,0.846014,0.727528,98523.942164,0.113998,0.010881
3,1,2016,4,278.596735,285.495557,285.537166,283.402897,281.431120,9.104211,282.787446,...,7.940460e+08,-0.058641,-0.015217,-0.012451,-0.088012,0.564882,0.108911,98572.488206,0.109738,0.007327
4,1,2016,5,284.854114,289.394813,289.120472,286.604616,285.235485,7.004377,287.983902,...,9.176412e+08,-0.083115,-0.022299,-0.011341,-0.118093,0.540203,-0.026081,98502.899633,0.120322,0.008150

In [6]:
greenery = pd.read_csv( COUNTY_DATA_DIR / 'greenery.csv')
greenery.head()

,COUNTYFP,year,month,NDVI,NDVI_binary,leaf_area_index_high_vegetation,leaf_area_index_low_vegetation
0,1,2016,1,NaN,NaN,1.366465,1.948488
1,1,2016,2,NaN,NaN,1.393319,1.949009
2,1,2016,3,NaN,NaN,1.651029,1.956439
3,1,2016,4,NaN,NaN,2.401848,1.972878
4,1,2016,5,NaN,NaN,3.670000,1.998367

In [10]:
landcover = pd.read_csv( COUNTY_DATA_DIR / 'landcover.csv')
landcover.head()

,COUNTYFP,bare-coverfraction,urban-coverfraction,crops-coverfraction,grass-coverfraction,moss-coverfraction,water-permanent-coverfraction,water-seasonal-coverfraction,shrub-coverfraction,snow-coverfraction,tree-coverfraction
0,1,1.000000,3.000000,18.800000,27.800000,0,1.000000,1.00000,3.600000,0,51.800000
1,3,1.000000,5.218750,74.006250,12.543750,0,1.000000,0.46875,2.043750,0,10.518750
2,5,1.228571,6.771429,56.657143,16.862857,0,2.691429,1.00000,2.400000,0,20.497143
3,7,1.000000,6.000000,14.000000,17.200000,0,1.200000,1.00000,3.000000,0,64.600000
4,9,1.423529,9.352941,28.552941,14.964706,0,1.000000,1.00000,2.388235,0,49.152941

In [8]:
sdi = pd.read_csv( COUNTY_DATA_DIR / 'sdi.csv')
sdi.head()

,COUNTYFP,County_population,SDI_score,PovertyLT100_FPL_score,Single_Parent_Fam_score,Education_LT12years_score,HHNo_Vehicle_score,HHRenter_Occupied_score,HHCrowding_score,Nonemployed_score,sdi,pct_Poverty_LT100,pct_Single_Parent_Fam,pct_Education_LT12years,pct_NonEmployed,pctHH_No_Vehicle,pctHH_Renter_Occupied,pctHH_Crowding
0,1,27776,80,93,90,90,74,29,11,98,0.955375,0.206555,0.176225,0.198241,0.644055,0.088166,0.291764,0.012180
1,3,103175,47,56,91,38,69,42,7,52,-0.061643,0.139258,0.179940,0.096970,0.372661,0.080394,0.329323,0.010603
2,5,53536,39,55,27,54,63,19,31,33,-0.318408,0.138034,0.111400,0.115253,0.339677,0.073174,0.262134,0.018171
3,7,97830,78,91,54,74,83,30,38,92,0.811973,0.198935,0.134982,0.139809,0.531281,0.098197,0.294777,0.020168
4,9,65917,81,100,59,41,68,74,34,98,1.024247,0.301582,0.140517,0.099800,0.657314,0.077892,0.421554,0.019107

In [9]:
icd1 = pd.read_csv('../data/raw/sathealth_dataset/icdl1_prev_ohio.csv')
icd1

      CBSAFP  year     code  count  count_patient  prevalence
0      10420  2016  A00-B99  10056          75040    0.134009
1      10420  2016  C00-D49   9797          75040    0.130557
2      10420  2016  D50-D89   4898          75040    0.065272
3      10420  2016  E00-E89  25231          75040    0.336234
4      10420  2016  F01-F99  19974          75040    0.266178
...      ...   ...      ...    ...            ...         ...
1964   49660  2021  R00-R99  10242          17942    0.570839
1965   49660  2021  S00-T88   3493          17942    0.194683
1966   49660  2021  U00-U85   1582          17942    0.088173
1967   49660  2021  V00-Y99   1102          17942    0.061420
1968   49660  2021  Z00-Z99  15156          17942    0.844722

[1969 rows x 6 columns]

In [11]:
time_varying_dfs = [airquality, climate, greenery]
static_dfs = [landcover, sdi]

for df in time_varying_dfs:
    df.set_index(['COUNTYFP', 'year', 'month'], inplace=True)
    
for df in static_dfs:
        df.set_index('COUNTYFP', inplace=True)

In [12]:
tvdf = pd.DataFrame()
for df in time_varying_dfs: 
    tvdf = pd.concat([tvdf, df], axis=1)

In [13]:
sdf = pd.DataFrame()
for df in static_dfs:
    sdf = pd.concat([sdf, df], axis=1)

In [14]:
tvdf

                     total_aerosol_optical_depth_at_550nm_surface  \
COUNTYFP year month
1        2016 1                                               NaN
              2                                               NaN
              3                                               NaN
              4                                               NaN
              5                                               NaN
...                                                           ...
175      2022 8                                          0.154756
              9                                          0.137054
              10                                         0.090350
              11                                         0.069374
              12                                         0.080952

                     particulate_matter_d_less_than_25_um_surface  \
COUNTYFP year month
1        2016 1                                               NaN
              2                                               NaN
              3                                               NaN
              4                                               NaN
              5                                               NaN
...                                                           ...
175      2022 8                                      8.271252e-09
              9                                      7.932409e-09
              10                                     7.371647e-09
              11                                     7.896651e-09
              12                                     6.854437e-09

                     NO2_column_number_density       ozone  \
COUNTYFP year month
1        2016 1                            NaN  323.208001
              2                            NaN  356.860486
              3                            NaN  332.589376
              4                            NaN  337.446316
              5                            NaN  350.506551
...                                        ...         ...
175      2022 8                       0.000078  311.625000
              9                       0.000075  295.947368
              10                      0.000077  296.619048
              11                      0.000072  281.904762
              12                      0.000076  311.666667

                     dewpoint_temperature_2m  temperature_2m  \
COUNTYFP year month
1        2016 1                   265.809779      272.191800
              2                   269.880511      275.427578
              3                   276.725622      282.880216
              4                   278.596735      285.495557
              5                   284.854114      289.394813
...                                      ...             ...
175      2022 8                   290.361096      295.404918
              9                   286.359566      291.967748
              10                  276.438225      285.054044
              11                  272.820241      279.962060
              12                  268.332067      273.298513

                     soil_temperature_level_1  soil_temperature_level_3  \
COUNTYFP year month
1        2016 1                    273.777254                278.618110
              2                    275.779540                276.860096
              3                    282.673310                280.923999
              4                    285.537166                283.402897
              5                    289.120472                286.604616
...                                       ...                       ...
175      2022 8                    296.114467                294.463538
              9                    293.117999                293.790153
              10                   286.228186                288.936600
              11                   281.109603                285.196755
              12                   274.941469                279.560640

                     lake_bottom_temperature  lake_mix_layer_depth  ...  \
COUNTYFP year month                                                 ...
1        2016 1                   274.626052              6.913982  ...
              2                   274.600529              8.128015  ...
              3                   279.385608             10.223921  ...
              4                   281.431120              9.104211  ...
              5                   285.235485              7.004377  ...
...                                      ...                   ...  ...
175      2022 8                   290.679102              4.395237  ...
              9                   288.771081              5.172552  ...
              10                  283.381456             10.312512  ...
              11                  280.062859             11.592308  ...
              12                  275.247991             10.879151  ...

                     total_evaporation_sum  u_component_of_wind_10m  \
COUNTYFP year month
1        2016 1                  -0.014871                 1.109925
              2                  -0.024876                 1.192782
              3                  -0.054091                 0.846014
              4                  -0.088012                 0.564882
              5                  -0.118093                 0.540203
...                                    ...                      ...
175      2022 8                  -0.111930                 0.467679
              9                  -0.076085                 0.769981
              10                 -0.042101                 1.180800
              11                 -0.024468                 1.914433
              12                 -0.012643                 1.509559

                     v_component_of_wind_10m  surface_pressure  \
COUNTYFP year month
1        2016 1                     0.475126      98676.667609
              2                     0.396486      98552.734185
              3                     0.727528      98523.942164
              4                     0.108911      98572.488206
              5                    -0.026081      98502.899633
...                                      ...               ...
175      2022 8                     0.570159      98467.381760
              9                     0.323688      98530.172024
              10                    1.131437      98505.179935
              11                    2.003213      98736.204702
              12                    1.757298      98666.951627

                     total_precipitation_sum  surface_runoff_sum      NDVI  \
COUNTYFP year month
1        2016 1                     0.042839            0.000810       NaN
              2                     0.138204            0.017986       NaN
              3                     0.113998            0.010881       NaN
              4                     0.109738            0.007327       NaN
              5                     0.120322            0.008150       NaN
...                                      ...                 ...       ...
175      2022 8                     0.099104            0.001961  0.836677
              9                     0.058525            0.000428  0.824143
              10                    0.033718            0.000208  0.381849
              11                    0.052435            0.002047  0.264485
              12                    0.049468            0.000533       NaN

                     NDVI_binary  leaf_area_index_high_vegetation  \
COUNTYFP year month
1        2016 1              NaN                         1.366465
              2              NaN                         1.393319
              3              NaN                         1.651029
              4              NaN                         2.401848
              5              NaN                         3.670000
...                          ...                              ...
175      2022 8         0.670684                         0.841320
              9         0.988147                         0.839919
              10        0.829206                         0.838300
              11        0.554976                         0.837925
              12        0.000000                         0.837317

                     leaf_area_index_low_vegetation
COUNTYFP year month
1        2016 1                            1.948488
              2                            1.949009
              3                            1.956439
              4                            1.972878
              5                            1.998367
...                                             ...
175      2022 8                            2.175350
              9                            1.523974
              10                           1.005421
              11                           0.823413
              12                           0.715264

[7392 rows x 36 columns]

In [15]:
sdf

,bare-coverfraction,urban-coverfraction,crops-coverfraction,grass-coverfraction,moss-coverfraction,water-permanent-coverfraction,water-seasonal-coverfraction,shrub-coverfraction,snow-coverfraction,tree-coverfraction,...,HHCrowding_score,Nonemployed_score,sdi,pct_Poverty_LT100,pct_Single_Parent_Fam,pct_Education_LT12years,pct_NonEmployed,pctHH_No_Vehicle,pctHH_Renter_Occupied,pctHH_Crowding
COUNTYFP,,,,,,,,,,,,,,,,,,,,,
1,1.000000,3.000000,18.800000,27.800000,0,1.000000,1.00000,3.600000,0,51.800000,...,11,98,0.955375,0.206555,0.176225,0.198241,0.644055,0.088166,0.291764,0.012180
3,1.000000,5.218750,74.006250,12.543750,0,1.000000,0.46875,2.043750,0,10.518750,...,7,52,-0.061643,0.139258,0.179940,0.096970,0.372661,0.080394,0.329323,0.010603
5,1.228571,6.771429,56.657143,16.862857,0,2.691429,1.00000,2.400000,0,20.497143,...,31,33,-0.318408,0.138034,0.111400,0.115253,0.339677,0.073174,0.262134,0.018171
7,1.000000,6.000000,14.000000,17.200000,0,1.200000,1.00000,3.000000,0,64.600000,...,38,92,0.811973,0.198935,0.134982,0.139809,0.531281,0.098197,0.294777,0.020168
9,1.423529,9.352941,28.552941,14.964706,0,1.000000,1.00000,2.388235,0,49.152941,...,34,98,1.024247,0.301582,0.140517,0.099800,0.657314,0.077892,0.421554,0.019107
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167,1.000000,3.000000,7.800000,13.800000,0,1.000000,1.00000,2.600000,0,77.000000,...,16,78,-0.335362,0.142097,0.133683,0.094011,0.446162,0.057864,0.263682,0.013732
169,1.000000,6.266667,25.986667,18.320000,0,1.000000,1.00000,2.840000,0,50.906667,...,35,28,-0.500762,0.112841,0.103686,0.134797,0.331333,0.094012,0.270400,0.019419
171,2.000000,8.000000,62.000000,17.600000,0,0.800000,1.00000,3.000000,0,14.600000,...,7,29,-1.056601,0.111674,0.114438,0.094571,0.332387,0.043340,0.229954,0.010736
173,2.000000,6.000000,71.600000,14.800000,0,1.000000,0.20000,2.200000,0,9.800000,...,1,14,-0.828912,0.129215,0.116886,0.056782,0.292019,0.046077,0.347447,0.005060
175,1.000000,6.000000,67.600000,15.200000,0,1.000000,0.00000,2.200000,0,13.800000,...,3,6,-1.403193,0.074418,0.146119,0.081143,0.263583,0.044709,0.259333,0.008039

In [40]:
icd1 = pd.read_csv(SATHEALTH_DATA_DIR / 'icdl1_prev_ohio.csv').set_index('CBSAFP') 
icd1

        year     code  count  count_patient  prevalence
CBSAFP
10420   2016  A00-B99  10056          75040    0.134009
10420   2016  C00-D49   9797          75040    0.130557
10420   2016  D50-D89   4898          75040    0.065272
10420   2016  E00-E89  25231          75040    0.336234
10420   2016  F01-F99  19974          75040    0.266178
...      ...      ...    ...            ...         ...
49660   2021  R00-R99  10242          17942    0.570839
49660   2021  S00-T88   3493          17942    0.194683
49660   2021  U00-U85   1582          17942    0.088173
49660   2021  V00-Y99   1102          17942    0.061420
49660   2021  Z00-Z99  15156          17942    0.844722

[1969 rows x 5 columns]

In [18]:
icd2 = pd.read_csv(SATHEALTH_DATA_DIR / 'icdl2_prev_ohio.csv').set_index('CBSAFP') 
mood_disorders = icd2[icd2['code']=='F30-F39']
mood_disorders_prev = mood_disorders[['year', 'prevalence']].rename(columns={'prevalence': 'mood_disorder_prevalence'})
mood_disorders_prev

        year  mood_disorder_prevalence
CBSAFP
10420   2016                  0.105850
10420   2017                  0.113062
10420   2018                  0.115720
10420   2019                  0.125098
10420   2020                  0.116675
...      ...                       ...
49660   2017                  0.096549
49660   2018                  0.101482
49660   2019                  0.112113
49660   2020                  0.112798
49660   2021                  0.121670

[92 rows x 2 columns]

In [19]:
icd3 = pd.read_csv(SATHEALTH_DATA_DIR / 'icdl3_prev_ohio.csv').set_index('CBSAFP') 
depression = icd3[icd3['code'] == 'F32']
depression_prev = depression[['year', 'prevalence']].rename(columns={'prevalence': 'depression_prevalence'})
depression_prev

        year  depression_prevalence
CBSAFP
10420   2016               0.071575
10420   2019               0.073754
10420   2020               0.066346
10420   2017               0.071619
10420   2018               0.070855
...      ...                    ...
49660   2016               0.065803
49660   2017               0.058328
49660   2021               0.067161
49660   2019               0.062402
49660   2020               0.061562

[92 rows x 2 columns]

In [35]:
cbsa_fips = pd.read_csv(RAW_DATA_DIR / 'cbsa_to_fips.csv')
cw = cbsa_fips[['cbsacode', 'fipscountycode']].rename(columns={'fipscountycode': 'COUNTYFP'})
print(len(cw.cbsacode.unique()))
print(len(cw.COUNTYFP.unique()))

935
244

In [39]:
cbsa_to_counties = (
    cw.groupby('cbsacode')['COUNTYFP']
      .apply(list)
      .to_dict()
)
cbsa_to_counties

{10100: [13, 45],
 10140: [27],
 10180: [59, 253, 441],
 10220: [123],
 10300: [91],
 10380: [3, 5, 11, 71, 99, 117, 131],
 10420: [133, 153],
 10460: [35],
 10480: [3, 21, 23],
 10500: [95, 177, 273, 321],
 10540: [43],
 10580: [1, 83, 91, 93, 95],
 10620: [167],
 10660: [47],
 10700: [95],
 10740: [1, 43, 57, 61],
 10760: [123],
 10780: [43, 79],
 10820: [41],
 10860: [47, 249],
 10900: [41, 25, 77, 95],
 10940: [57],
 10980: [7],
 11020: [13],
 11060: [65],
 11100: [11, 65, 359, 375, 381],
 11140: [249, 261],
 11180: [15, 169],
 11200: [15],
 11220: [57],
 11260: [20, 170],
 11360: [85],
 11380: [3],
 11420: [151],
 11460: [161],
 11500: [15],
 11540: [15, 87],
 11580: [27],
 11620: [19],
 11640: [13, 27, 65, 115],
 11660: [19],
 11680: [35],
 11700: [21, 89, 115],
 11740: [5],
 11820: [7],
 11860: [5],
 11900: [9],
 11940: [107, 121],
 11980: [213],
 12020: [59, 195, 219, 221],
 12060: [13,
  15,
  35,
  45,
  57,
  63,
  67,
  77,
  85,
  89,
  97,
  113,
  117,
  121,
  135,
  143,
  149,
  151,
  159,
  187,
  199,
  211,
  217,
  223,
  227,
  231,
  247,
  255,
  297],
 12100: [1, 9],
 12140: [33],
 12180: [11],
 12220: [81, 87],
 12260: [33, 73, 181, 189, 245, 3, 37],
 12300: [11],
 12380: [99],
 12420: [21, 55, 209, 453, 491],
 12460: [87],
 12520: [1],
 12540: [29],
 12580: [3, 5, 13, 25, 27, 35, 510],
 12620: [19],
 12660: [111],
 12700: [1],
 12740: [23],
 12780: [147],
 12860: [37],
 12900: [63],
 12940: [5, 7, 33, 37, 47, 63, 77, 91, 121, 125],
 12980: [25],
 13020: [17],
 13060: [321],
 13100: [67],
 13140: [199, 245, 361],
 13180: [27],
 13220: [19, 81],
 13260: [93],
 13300: [25],
 13340: [91],
 13380: [73],
 13420: [7],
 13460: [13, 17, 31],
 13540: [3],
 13660: [107],
 13700: [227],
 13740: [9, 95, 111],
 13780: [7, 107],
 13820: [7, 9, 21, 73, 115, 117, 127],
 13860: [27],
 13900: [15, 59, 65],
 13940: [11],
 13980: [63, 71, 121, 155, 750],
 14010: [113],
 14020: [105, 119],
 14100: [37],
 14140: [185, 55],
 14180: [93],
 14220: [117],
 14260: [1, 15, 27, 45, 73],
 14300: [147],
 14380: [189],
 14420: [233],
 14460: [9, 17, 21, 23, 25, 15, 17],
 14500: [13],
 14540: [3, 31, 61, 227],
 14580: [31],
 14620: [83],
 14660: [21, 35],
 14700: [213],
 14710: [25],
 14720: [65, 117],
 14740: [35],
 14780: [477],
 14820: [175],
 14860: [120, 190],
 14940: [71, 3],
 15020: [85],
 15060: [15],
 15100: [11],
 15180: [61],
 15220: [49],
 15260: [25, 127, 191],
 15340: [33],
 15380: [29, 63],
 15420: [31, 67],
 15460: [71, 57],
 15500: [1],
 15540: [7, 11, 13],
 15580: [93],
 15620: [113, 165],
 15660: [129],
 15700: [19],
 15740: [59],
 15780: [13, 103],
 15820: [87, 217],
 15860: [43],
 15900: [57],
 15940: [19, 151],
 15980: [71],
 16020: [3, 17, 31],
 16060: [77],
 16100: [15],
 16140: [27],
 16180: [510],
 16220: [25],
 16260: [21],
 16300: [11, 105, 113],
 16340: [233],
 16380: [107],
 16460: [121],
 16500: [41],
 16540: [55],
 16580: [19, 53, 147],
 16620: [5, 15, 39],
 16660: [29],
 16700: [15, 19, 35],
 16740: [7, 25, 71, 97, 109, 119, 159, 179, 23, 57, 91],
 16820: [3, 65, 79, 125, 540],
 16860: [47, 83, 295, 65, 115, 153],
 16940: [21],
 16980: [31, 37, 43, 63, 89, 93, 97, 111, 197, 73, 89, 111, 127],
 17020: [7],
 17060: [141],
 17140: [29, 47, 115, 15, 23, 37, 77, 81, 117, 191, 15, 17, 25, 61, 165],
 17220: [17, 33, 91],
 17260: [27],
 17300: [47, 221, 125, 161],
 17340: [33],
 17380: [11],
 17410: [7, 35, 55, 85, 93, 103],
 17420: [11, 139],
 17500: [43, 51],
 17540: [45],
 17580: [9, 41],
 17620: [43, 133],
 17640: [123],
 17650: [29],
 17660: [55],
 17740: [23],
 17780: [41, 51, 395],
 17820: [41, 119],
 17860: [19, 53, 89],
 17900: [17, 39, 55, 63, 79, 81],
 17980: [113, 53, 145, 197, 215, 259, 263],
 18020: [5],
 18060: [87, 103],
 18100: [37, 141],
 18140: [41, 45, 49, 73, 89, 97, 117, 127, 129, 159],
 18180: [13],
 18220: [41],
 18260: [87, 133, 141, 185],
 18300: [11],
 18340: [51, 121, 125, 235],
 18380: [81],
 18420: [3],
 18460: [137],
 18500: [101],
 18580: [7, 355, 409],
 18620: [349],
 18660: [23],
 18700: [3],
 18740: [31],
 18820: [107],
 18860: [15],
 18880: [91, 131],
 18900: [35],
 18980: [43],
 19060: [1, 57],
 19100: [85, 113, 121, 139, 231, 251, 257, 367, 397, 439, 497],
 19140: [213, 313],
 19180: [183],
 19220: [21, 137],
 19260: [143, 590],
 19300: [3],
 19340: [73, 131, 161, 163],
 19430: [57, 109, 113],
 19460: [79, 103],
 19500: [115],
 19540: [1],
 19580: [39],
 19620: [465],
 19660: [35, 127],
 19700: [29],
 19740: [1, 5, 14, 19, 31, 35, 39, 47, 59, 93],
 19760: [11],
 19780: [49, 77, 99, 121, 153, 181],
 19810: [5],
 19820: [87, 93, 99, 125, 147, 163],
 19860: [7, 25, 89],
 19940: [103],
 19980: [57],
 20020: [61, 67, 69],
 20060: [3, 69],
 20100: [1],
 20140: [167, 175],
 20180: [33],
 20220: [61],
 20260: [17, 137, 31],
 20300: [341],
 20340: [137],
 20420: [67],
 20460: [13],
 20500: [37, 63, 135, 145],
 20540: [45],
 20580: [323],
 20660: [41],
 20700: [89],
 20740: [17, 35],
 20780: [37],
 20820: [35, 49],
 20900: [481],
 20940: [25],
 20980: [139],
 21020: [139],
 21060: [93, 123],
 21120: [9],
 21140: [39],
 21180: [83],
 21220: [7, 11],
 21260: [37],
 21300: [15],
 21340: [141, 229],
 21380: [17, 111],
 21420: [47],
 21460: [31],
 21500: [49],
 21540: [41],
 21580: [39],
 21640: [5, 239],
 21660: [39],
 21700: [23],
 21740: [33, 41],
 21780: [129, 163, 173],
 21820: [90],
 21860: [91],
 21900: [49],
 21980: [1],
 22020: [27, 17],
 22060: [131],
 22100: [187],
 22140: [45],
 22180: [51, 93],
 22190: [103],
 22220: [7, 87, 143],
 22260: [111],
 22300: [63],
 22340: [17],
 22380: [5],
 22420: [49],
 22500: [31, 41],
 22520: [33, 77],
 22540: [39],
 22580: [161],
 22620: [123],
 22660: [69],
 22700: [187],
 22780: [169],
 22800: [111],
 22820: [87],
 22840: [49],
 22900: [33, 131, 135],
 23060: [3, 179, 183],
 23140: [23],
 23180: [5, 73],
 23190: [213],
 23240: [171],
 23300: [177],
 23340: [53],
 23380: [143],
 23420: [19, 39],
 23460: [55],
 23500: [21],
 23540: [1, 41, 75],
 23580: [139],
 23620: [97],
 23660: [95],
 23680: [53],
 23700: [31],
 23780: [55],
 23820: [3, 5],
 23900: [1],
 23940: [5],
 23980: [9, 169],
 24020: [113, 115],
 24100: [35],
 24140: [191],
 24180: [221],
 24220: [119, 35],
 24260: [79, 93, 121],
 24300: [77],
 24330: [61],
 24340: [15, 67, 81, 117, 139],
 24420: [33],
 24460: [9],
 24500: [13],
 24540: [123],
 24580: [9, 61, 83],
 24600: [133],
 24620: [59],
 24640: [11],
 24660: [81, 151, 157],
 24700: [31],
 24740: [151],
 24780: [147],
 24820: [37],
 24860: [7, 45, 59, 77],
 24900: [15, 83],
 24940: [1, 47],
 24980: [43, 97],
 25020: [15, 57, 109],
 25060: [45, 47, 59, 131],
 25100: [139],
 25180: [43, 3, 65],
 25200: [13, 25, 63],
 25220: [105],
 25260: [31],
 25300: [127, 173],
 25420: [41, 43, 99],
 25460: [9, 101],
 25500: [165, 660],
 25540: [110, 130],
 25580: [1, 35, 181],
 25620: [35, 73, 111],
 25700: [51],
 25720: [43, 51],
 25740: [7, 43, 49],
 25770: [103],
 25775: [101, 233],
 25780: [181],
 25820: [117],
 25840: [49, 59],
 25850: [85],
 25860: [3, 23, 27, 35],
 25880: [59],
 25900: [1],
 25940: [13, 53],
 25980: [179, 183],
 26020: [25],
 26090: [5],
 26140: [17],
 26220: [27],
 26300: [51],
 26340: [61, 83],
 26380: [57, 109],
 26420: [15, 39, 71, 157, 167, 201, 291, 339, 407, 473],
 26460: [21],
 26500: [61],
 26540: [69],
 26580: [19, 43, 89, 127, 87, 11, 79, 99],
 26620: [83, 89],
 26660: [471],
 26700: [5],
 26740: [155],
 26780: [85],
 26820: [19, 23, 51],
 26860: [63],
 26900: [11, 13, 57, 59, 63, 81, 95, 97, 109, 145, 159],
 26980: [103, 183],
 27020: [43, 37],
 27060: [109],
 27100: [75],
 27140: [29, 49, 51, 89, 121, 123, 127, 163],
 27180: [23, 33, 53, 113],
 27220: [81, 39],
 27260: [3, 19, 31, 89, 109],
 27300: [137, 171],
 27340: [133],
 27380: [73],
 27420: [93],
 27460: [13],
 27500: [105],
 27540: [37],
 27600: [157],
 27620: [27, 51, 135, 151],
 27700: [305],
 27740: [19, 171, 179],
 27780: [21],
 27860: [31, 111],
 27900: [21, 97, 145],
 27940: [110],
 27980: [5, 9],
 28020: [77],
 28060: [29],
 28100: [91],
 28140: [91, 103, 107, 121, 209, 13, 25, 37, 47, 49, 95, 107, 165, 177],
 28180: [7],
 28260: [19, 99],
 28300: [5],
 28340: [113],
 28380: [69],
 28420: [5, 21],
 28450: [59],
 28500: [265],
 28540: [130],
 28580: [87],
 28620: [55],
 28660: [27, 99, 281],
 28680: [39],
 28700: [73, 163, 169, 191, 520],
 28740: [111],
 28780: [273],
 28820: [107],
 28860: [1, 197],
 28880: [27, 71],
 28900: [35],
 28940: [1, 9, 13, 57, 93, 105, 129, 145, 173],
 29020: [67],
 29060: [1],
 29100: [55, 63, 123],
 29180: [1, 55, 99, 113],
 29200: [7, 15, 157, 171],
 29260: [61],
 29300: [17, 285],
 29340: [19, 23, 53],
 29380: [23],
 29420: [15],
 29460: [105],
 29470: [137],
 29540: [71],
 29620: [37, 45, 65],
 29660: [1],
 29700: [479],
 29720: [81],
 29740: [13],
 29780: [33, 47],
 29820: [3],
 29860: [61, 67],
 29900: [165],
 29940: [45],
 29980: [99],
 30020: [31, 33],
 30060: [105],
 30140: [75],
 30150: [9, 19, 17, 27],
 30180: [149],
 30260: [119],
 30280: [117],
 30300: [69, 3],
 30340: [1],
 30380: [87],
 30420: [47, 73],
 30460: [17, 49, 67, 113, 209, 239],
 30500: [9, 37],
 30580: [175],
 30620: [3],
 30660: [107],
 30700: [109, 159],
 30780: [45, 53, 85, 105, 119, 125],
 30820: [35],
 30860: [41, 5],
 30900: [17],
 30980: [183, 203, 401, 459],
 31020: [15],
 31060: [28],
 31080: [37, 59],
 31140: [19, 43, 61, 175, 29, 103, 111, 163, 179, 185, 211, 215],
 31180: [79, 107, 169, 219, 303, 305],
 31220: [105],
 31260: [5],
 31300: [155],
 31340: [9, 11, 19, 31, 680],
 31380: [109],
 31420: [21, 79, 169, 207, 289],
 31500: [77],
 31540: [21, 25, 45, 49],
 31580: [107],
 31620: [27],
 31680: [59],
 31700: [11],
 31740: [61, 149, 161],
 31820: [71],
 31860: [13, 103],
 31900: [139],
 31930: [167],
 31940: [109, 75],
 31980: [53],
 32000: [111],
 32020: [101],
 32060: [199],
 32100: [103],
 32140: [83],
 32180: [195],
 32260: [127],
 32280: [183],
 32300: [89, 690],
 32340: [147],
 32380: [33, 195],
 32390: [89],
 32420: [23, 67, 79, 97, 121, 125],
 32460: [83],
 32540: [121],
 32580: [215],
 32620: [113, 147],
 32660: [177],
 32700: [113],
 32740: [39],
 32780: [29],
 32820: [35, 9, 33, 93, 137, 143, 47, 157, 167],
 32860: [33],
 32900: [47],
 32940: [23, 75],
 33020: [7],
 33060: [115],
 33100: [11, 86, 99],
 33140: [91],
 33180: [13],
 33220: [111],
 33260: [317, 329],
 33300: [9],
 33340: [79, 89, 131, 133],
 33380: [119],
 33420: [363],
 33460: [3, 19, 25, 37, 53, 59, 79, 95, 123, 139, 141, 163, 171, 93, 109],
 33500: [49, 75, 101],
 33540: [61, 63],
 33580: [35, 61, 111],
 33620: [175],
 33660: [97],
 33700: [99],
 33740: [67, 73, 83, 111],
 33780: [115],
 33860: [1, 51, 85, 101],
 33900: [181],
 33910: [105],
 33940: [85],
 33980: [31],
 34020: [101],
 34060: [61, 77],
 34100: [63, 89],
 34140: [57],
 34180: [25],
 34220: [71],
 34260: [5],
 34300: [39],
 34340: [171],
 34380: [73],
 34420: [63, 343, 449],
 34460: [11, 165, 173],
 34500: [81],
 34540: [83],
 34580: [57],
 34620: [35],
 34660: [35],
 34680: [43],
 34700: [139],
 34740: [121],
 34780: [101],
 34820: [51],
 34860: [347],
 34880: [19],
 34900: [55],
 34940: [21],
 34980: [15, 21, 37, 43, 81, 111, 119, 147, 149, 159, 165, 169, 187, 189],
 35020: [29, 1, 63],
 35060: [69],
 35100: [49, 103, 137],
 35140: [71],
 35220: [65],
 35300: [170],
 35340: [45],
 35380: [51, 71, 75, 87, 89, 93, 95],
 35420: [157],
 35440: [41],
 35460: [29],
 35580: [15],
 35620: [3,
  13,
  17,
  19,
  23,
  25,
  27,
  29,
  31,
  35,
  37,
  39,
  5,
  47,
  59,
  61,
  79,
  81,
  85,
  87,
  103,
  119],
 35660: [21],
 35700: [23],
 35740: [119, 139, 167],
 35820: [111, 113],
 35840: [81, 115],
 35900: [193],
 35940: [77],
 35980: [180],
 36020: [29],
 36100: [83],
 36180: [47],
 36220: [135],
 36260: [11, 29, 57],
 36340: [121],
 36380: [93],
 36420: [17, 27, 51, 81, 83, 87, 109],
 36460: [9],
 36500: [67],
 36540: [85, 129, 155, 25, 55, 153, 155, 177],
 36580: [77],
 36620: [75, 45],
 36660: [97],
 36700: [75],
 36740: [69, 95, 97, 117],
 36780: [139],
 36820: [123],
 36830: [1],
 36837: [11, 99, 155],
 36840: [59],
 36900: [179],
 36940: [147],
 36980: [59, 149],
 37020: [155],
 37060: [71, 161],
 37100: [111],
 37120: [45],
 37140: [127, 7, 39, 139, 145],
 37220: [23],
 37260: [107],
 37300: [1],
 37340: [9],
 37420: [179, 393],
 37460: [5, 133],
 37500: [55],
 37540: [79],
 37580: [277, 387],
 37620: [105, 107],
 37740: [7],
 37800: [125],
 37860: [33, 113],
 37900: [123, 143, 175, 179, 203],
 37940: [103],
 37950: [47],
 37980: [3, 15, 5, 7, 15, 33, 17, 29, 45, 91, 101],
 38060: [13, 21],
 38100: [109],
 38180: [65, 117],
 38210: [71, 195],
 38220: [25, 69],
 38240: [125],
 38260: [37],
 38300: [3, 5, 7, 19, 51, 73, 125, 129],
 38340: [3],
 38380: [153, 189],
 38420: [43],
 38460: [19],
 38500: [99],
 38540: [5],
 38620: [71],
 38660: [59, 75, 111, 113, 149, 153],
 38700: [105],
 38740: [23],
 38820: [9],
 38860: [5, 23, 31],
 38900: [5, 9, 51, 67, 71, 11, 59],
 38920: [57],
 38940: [85, 111],
 39020: [145],
 39040: [31],
 39060: [107],
 39150: [25],
 39220: [7],
 39300: [5, 1, 3, 5, 7, 9],
 39340: [23, 49],
 39380: [101],
 39420: [75],
 39460: [15],
 39480: [150],
 39500: [1, 111],
 39540: [101],
 39580: [69, 101, 183],
 39660: [33, 93, 103],
 39700: [489],
 39740: [11],
 39780: [103],
 39820: [89],
 39860: [49],
 39900: [19, 29, 31],
 39940: [43, 65],
 39960: [5],
 39980: [177],
 40060: [7,
  36,
  41,
  53,
  75,
  85,
  87,
  97,
  101,
  127,
  145,
  149,
  183,
  570,
  670,
  730,
  760],
 40080: [65, 151, 203],
 40090: [45, 97],
 40100: [427],
 40140: [65, 71],
 40180: [13],
 40220: [23, 45, 67, 161, 770, 775],
 40260: [83, 131],
 40300: [141],
 40340: [39, 45, 109, 157],
 40380: [51, 55, 69, 73, 117],
 40420: [7, 201],
 40460: [153],
 40540: [37],
 40580: [65, 127],
 40620: [161],
 40660: [115],
 40700: [19],
 40740: [5],
 40760: [27],
 40770: [59],
 40780: [115, 149],
 40820: [61],
 40860: [21],
 40900: [17, 61, 67, 113],
 40940: [9],
 40980: [145],
 41060: [9, 145],
 41100: [53],
 41140: [43, 3, 21, 63],
 41180: [5, 13, 27, 83, 117, 119, 133, 163, 71, 99, 113, 183, 189, 219, 510],
 41260: [47],
 41400: [29],
 41420: [47, 53],
 41460: [143, 169],
 41500: [53],
 41540: [39, 45],
 41620: [35, 45],
 41660: [235, 451],
 41700: [13, 19, 29, 91, 187, 259, 325, 493],
 41740: [73],
 41760: [17],
 41780: [43, 123],
 41820: [105],
 41860: [1, 13, 41, 75, 81],
 41940: [69, 85],
 41980: [7,
  9,
  17,
  19,
  21,
  25,
  29,
  31,
  33,
  35,
  37,
  39,
  41,
  45,
  47,
  51,
  53,
  54,
  61,
  63,
  69,
  77,
  85,
  87,
  89,
  91,
  95,
  101,
  103,
  105,
  107,
  119,
  127,
  129,
  135,
  137,
  139,
  143,
  145,
  151],
 42020: [79],
 42100: [87],
 42140: [49],
 42200: [83],
 42220: [97],
 42300: [33],
 42340: [29, 51, 103],
 42380: [15],
 42420: [7, 157],
 42460: [71],
 42540: [69, 79, 131],
 42580: [5],
 42620: [145],
 42660: [33, 53, 61],
 42680: [61],
 42700: [55],
 42740: [159],
 42780: [109],
 42820: [47],
 42860: [73],
 42900: [99],
 42940: [155],
 42980: [71],
 43020: [78, 115],
 43060: [125],
 43100: [117],
 43140: [45],
 43180: [3],
 43220: [45],
 43260: [33],
 43300: [181],
 43320: [17],
 43340: [15, 17, 31],
 43380: [149],
 43420: [3],
 43460: [133, 201],
 43500: [17],
 43580: [193, 43, 127],
 43620: [133, 83, 87, 99, 125],
 43640: [103],
 43660: [415],
 43700: [199],
 43740: [111],
 43760: [109],
 43780: [141, 27],
 43890: [81],
 43900: [83, 87],
 43940: [81],
 43980: [41],
 44020: [59],
 44060: [63, 65],
 44100: [129, 167],
 44140: [13],
 44180: [43, 59, 77, 167, 225],
 44220: [23],
 44260: [105, 155],
 44300: [27],
 44340: [31, 109],
 44420: [15, 790, 820],
 44460: [81, 107],
 44500: [143],
 44540: [75],
 44580: [195],
 44620: [97],
 44660: [119],
 44700: [77],
 44740: [21],
 44780: [149],
 44860: [223],
 44900: [55],
 44940: [85],
 44980: [93, 97],
 45000: [35],
 45020: [353],
 45060: [53, 67, 75],
 45140: [21],
 45180: [37, 121],
 45220: [39, 65, 73, 129],
 45300: [53, 57, 101, 103],
 45340: [55],
 45380: [21],
 45460: [21, 153, 165, 167],
 45500: [81, 91, 37],
 45520: [65],
 45580: [293],
 45620: [131, 275],
 45660: [147],
 45700: [277, 287],
 45740: [257],
 45780: [51, 95, 173],
 45820: [85, 87, 139, 177, 197],
 45860: [160],
 45880: [389],
 45900: [19, 55, 79, 89],
 45940: [21],
 45980: [109],
 46020: [57],
 46060: [19],
 46100: [31, 127],
 46140: [37, 111, 113, 117, 131, 143, 145],
 46180: [57, 81, 117],
 46220: [63, 65, 107, 125],
 46300: [53, 83],
 46340: [423],
 46380: [45],
 46460: [131],
 46500: [21],
 46520: [3],
 46540: [43, 65],
 46580: [141],
 46620: [463],
 46660: [27, 101, 173, 185],
 46700: [95],
 46780: [161],
 46820: [27],
 46860: [47],
 46900: [487],
 46980: [149],
 47020: [175, 469],
 47080: [209, 279],
 47180: [83],
 47220: [11],
 47240: [7],
 47260: [29,
  53,
  73,
  73,
  93,
  95,
  115,
  181,
  199,
  550,
  650,
  700,
  710,
  735,
  740,
  800,
  810,
  830],
 47300: [107],
 47340: [169],
 47380: [35, 145, 309],
 47420: [167, 77],
 47460: [71],
 47540: [11],
 47580: [153, 225],
 47620: [123],
 47660: [101],
 47700: [85],
 47780: [27],
 47820: [13],
 47900: [1,
  17,
  21,
  31,
  33,
  13,
  43,
  47,
  59,
  61,
  107,
  153,
  157,
  177,
  179,
  187,
  510,
  600,
  610,
  630,
  683,
  685,
  37],
 47920: [47],
 47930: [140],
 47940: [13, 17, 75],
 47980: [29],
 48020: [55],
 48060: [45],
 48140: [73],
 48180: [229, 299],
 48200: [87],
 48220: [39, 149],
 48260: [81, 9, 29],
 48300: [7, 17],
 48460: [91],
 48540: [13, 51, 69],
 48580: [127],
 48620: [15, 79, 173, 191],
 48660: [9, 77, 485],
 48680: [119],
 48700: [81],
 48780: [105],
 48820: [67],
 48900: [19, 129, 141],
 48940: [27],
 48980: [195],
 49010: [51],
 49020: [69, 840, 27],
 49080: [13],
 49100: [169],
 49180: [57, 59, 67, 169, 197],
 49220: [141],
 49260: [153],
 49300: [169],
 49340: [27],
 49380: [105],
 49420: [77],
 49460: [135],
 49620: [133],
 49660: [99, 155],
 49700: [101, 115],
 49740: [27],
 49780: [119],
 49820: [505]}

In [41]:
icd1

        year     code  count  count_patient  prevalence
CBSAFP
10420   2016  A00-B99  10056          75040    0.134009
10420   2016  C00-D49   9797          75040    0.130557
10420   2016  D50-D89   4898          75040    0.065272
10420   2016  E00-E89  25231          75040    0.336234
10420   2016  F01-F99  19974          75040    0.266178
...      ...      ...    ...            ...         ...
49660   2021  R00-R99  10242          17942    0.570839
49660   2021  S00-T88   3493          17942    0.194683
49660   2021  U00-U85   1582          17942    0.088173
49660   2021  V00-Y99   1102          17942    0.061420
49660   2021  Z00-Z99  15156          17942    0.844722

[1969 rows x 5 columns]

In [ ]:
icd1 = pd.merge(icd1, cw, left_index=True, right_on='cbsacode').set_index('COUNTYFP')
icd1

In [21]:
icd1.code.unique()

array(['A00-B99', 'C00-D49', 'D50-D89', 'E00-E89', 'F01-F99', 'G00-G99',
       'H00-H59', 'H60-H95', 'I00-I99', 'J00-J99', 'K00-K95', 'L00-L99',
       'M00-M99', 'N00-N99', 'O00-O9A', 'P00-P96', 'Q00-Q99', 'R00-R99',
       'S00-T88', 'V00-Y99', 'Z00-Z99', 'U00-U85'], dtype=object)

In [22]:
sdf.info()

<class 'pandas.core.frame.DataFrame'>
Index: 88 entries, 1 to 175
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   bare-coverfraction             88 non-null     float64
 1   urban-coverfraction            88 non-null     float64
 2   crops-coverfraction            88 non-null     float64
 3   grass-coverfraction            88 non-null     float64
 4   moss-coverfraction             88 non-null     int64
 5   water-permanent-coverfraction  88 non-null     float64
 6   water-seasonal-coverfraction   88 non-null     float64
 7   shrub-coverfraction            88 non-null     float64
 8   snow-coverfraction             88 non-null     int64
 9   tree-coverfraction             88 non-null     float64
 10  County_population              88 non-null     int64
 11  SDI_score                      88 non-null     int64
 12  PovertyLT100_FPL_score         88 non-null     int64
 13  Single_Parent_Fam_score        88 non-null     int64
 14  Education_LT12years_score      88 non-null     int64
 15  HHNo_Vehicle_score             88 non-null     int64
 16  HHRenter_Occupied_score        88 non-null     int64
 17  HHCrowding_score               88 non-null     int64
 18  Nonemployed_score              88 non-null     int64
 19  sdi                            88 non-null     float64
 20  pct_Poverty_LT100              88 non-null     float64
 21  pct_Single_Parent_Fam          88 non-null     float64
 22  pct_Education_LT12years        88 non-null     float64
 23  pct_NonEmployed                88 non-null     float64
 24  pctHH_No_Vehicle               88 non-null     float64
 25  pctHH_Renter_Occupied          88 non-null     float64
 26  pctHH_Crowding                 88 non-null     float64
dtypes: float64(16), int64(11)
memory usage: 19.2 KB

In [23]:
tvdf.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 7392 entries, (np.int64(1), np.int64(2016), np.int64(1)) to (np.int64(175), np.int64(2022), np.int64(12))
Data columns (total 36 columns):
 #   Column                                                     Non-Null Count  Dtype
---  ------                                                     --------------  -----
 0   total_aerosol_optical_depth_at_550nm_surface               6952 non-null   float64
 1   particulate_matter_d_less_than_25_um_surface               6952 non-null   float64
 2   NO2_column_number_density                                  4752 non-null   float64
 3   ozone                                                      7392 non-null   float64
 4   dewpoint_temperature_2m                                    7392 non-null   float64
 5   temperature_2m                                             7392 non-null   float64
 6   soil_temperature_level_1                                   7392 non-null   float64
 7   soil_temperature_level_3                                   7392 non-null   float64
 8   lake_bottom_temperature                                    7392 non-null   float64
 9   lake_mix_layer_depth                                       7392 non-null   float64
 10  lake_mix_layer_temperature                                 7392 non-null   float64
 11  lake_total_layer_temperature                               7392 non-null   float64
 12  snow_albedo                                                7392 non-null   float64
 13  snow_cover                                                 7392 non-null   float64
 14  snow_density                                               7392 non-null   float64
 15  snow_depth                                                 7392 non-null   float64
 16  skin_reservoir_content                                     7392 non-null   float64
 17  volumetric_soil_water_layer_1                              7392 non-null   float64
 18  volumetric_soil_water_layer_3                              7392 non-null   float64
 19  surface_latent_heat_flux_sum                               7392 non-null   float64
 20  surface_net_solar_radiation_sum                            7392 non-null   float64
 21  surface_solar_radiation_downwards_sum                      7392 non-null   float64
 22  surface_thermal_radiation_downwards_sum                    7392 non-null   float64
 23  evaporation_from_bare_soil_sum                             7392 non-null   float64
 24  evaporation_from_the_top_of_canopy_sum                     7392 non-null   float64
 25  evaporation_from_open_water_surfaces_excluding_oceans_sum  7392 non-null   float64
 26  total_evaporation_sum                                      7392 non-null   float64
 27  u_component_of_wind_10m                                    7392 non-null   float64
 28  v_component_of_wind_10m                                    7392 non-null   float64
 29  surface_pressure                                           7392 non-null   float64
 30  total_precipitation_sum                                    7392 non-null   float64
 31  surface_runoff_sum                                         7392 non-null   float64
 32  NDVI                                                       3766 non-null   float64
 33  NDVI_binary                                                5016 non-null   float64
 34  leaf_area_index_high_vegetation                            7392 non-null   float64
 35  leaf_area_index_low_vegetation                             7392 non-null   float64
dtypes: float64(36)
memory usage: 2.1 MB

In [24]:
add_cols = [col for col in tvdf.columns if '_sum' in col]
non_add_cols = [col for col in tvdf.columns if '_sum' not in col]

In [25]:
tvdf.groupby(['COUNTYFP', 'year'])[add_cols].sum()
tvdf.groupby(['COUNTYFP', 'year'])[non_add_cols].mean()

yearly_tvdf = tvdf.groupby(['COUNTYFP', 'year'])[add_cols].sum().join(tvdf.groupby(['COUNTYFP', 'year'])[non_add_cols].mean())
yearly_tvdf

               surface_latent_heat_flux_sum  surface_net_solar_radiation_sum  \
COUNTYFP year
1        2016                 -2.245064e+09                     4.588028e+09
         2017                 -2.381129e+09                     4.515247e+09
         2018                 -2.312478e+09                     4.299157e+09
         2019                 -2.310947e+09                     4.495104e+09
         2020                 -2.240104e+09                     4.405690e+09
...                                     ...                              ...
175      2018                 -1.929416e+09                     3.981338e+09
         2019                 -1.871159e+09                     4.050524e+09
         2020                 -1.959273e+09                     4.205512e+09
         2021                 -2.048442e+09                     4.187213e+09
         2022                 -1.971572e+09                     4.277757e+09

               surface_solar_radiation_downwards_sum  \
COUNTYFP year
1        2016                           5.497038e+09
         2017                           5.383814e+09
         2018                           5.170547e+09
         2019                           5.380707e+09
         2020                           5.258213e+09
...                                              ...
175      2018                           5.117686e+09
         2019                           5.151902e+09
         2020                           5.290219e+09
         2021                           5.445625e+09
         2022                           5.476614e+09

               surface_thermal_radiation_downwards_sum  \
COUNTYFP year
1        2016                             1.029385e+10
         2017                             1.029233e+10
         2018                             1.037388e+10
         2019                             1.034291e+10
         2020                             1.034631e+10
...                                                ...
175      2018                             1.005559e+10
         2019                             1.002667e+10
         2020                             1.004891e+10
         2021                             1.004956e+10
         2022                             9.828283e+09

               evaporation_from_bare_soil_sum  \
COUNTYFP year
1        2016                       -0.608775
         2017                       -0.647583
         2018                       -0.600183
         2019                       -0.620441
         2020                       -0.588873
...                                       ...
175      2018                       -0.533101
         2019                       -0.531189
         2020                       -0.558878
         2021                       -0.600712
         2022                       -0.564776

               evaporation_from_the_top_of_canopy_sum  \
COUNTYFP year
1        2016                               -0.148960
         2017                               -0.165131
         2018                               -0.198896
         2019                               -0.166044
         2020                               -0.170820
...                                               ...
175      2018                               -0.122686
         2019                               -0.103084
         2020                               -0.100886
         2021                               -0.097959
         2022                               -0.090412

               evaporation_from_open_water_surfaces_excluding_oceans_sum  \
COUNTYFP year
1        2016                                          -0.113297
         2017                                          -0.117489
         2018                                          -0.100206
         2019                                          -0.113384
         2020                                          -0.114033
...                                                          ...
175      2018                                          -0.087122
         2019                                          -0.093507
         2020                                          -0.101261
         2021                                          -0.103354
         2022                                          -0.101842

               total_evaporation_sum  total_precipitation_sum  \
COUNTYFP year
1        2016              -0.896807                 1.117447
         2017              -0.951710                 1.277161
         2018              -0.923600                 1.570293
         2019              -0.923404                 1.507736
         2020              -0.895300                 1.403282
...                              ...                      ...
175      2018              -0.768484                 1.379405
         2019              -0.746165                 1.186287
         2020              -0.781190                 1.079575
         2021              -0.817454                 1.114219
         2022              -0.785057                 0.953699

               surface_runoff_sum  ...  skin_reservoir_content  \
COUNTYFP year                      ...
1        2016            0.077646  ...                0.000076
         2017            0.098897  ...                0.000080
         2018            0.118903  ...                0.000111
         2019            0.135478  ...                0.000084
         2020            0.112068  ...                0.000082
...                           ...  ...                     ...
175      2018            0.080553  ...                0.000056
         2019            0.080074  ...                0.000046
         2020            0.040048  ...                0.000040
         2021            0.061494  ...                0.000052
         2022            0.049729  ...                0.000038

               volumetric_soil_water_layer_1  volumetric_soil_water_layer_3  \
COUNTYFP year
1        2016                       0.338182                       0.329230
         2017                       0.355092                       0.349952
         2018                       0.372075                       0.371587
         2019                       0.352191                       0.347395
         2020                       0.349805                       0.340653
...                                      ...                            ...
175      2018                       0.371826                       0.370014
         2019                       0.348711                       0.336329
         2020                       0.340364                       0.319670
         2021                       0.350755                       0.347050
         2022                       0.330390                       0.307934

               u_component_of_wind_10m  v_component_of_wind_10m  \
COUNTYFP year
1        2016                 0.672390                 0.301271
         2017                 0.694002                 0.402490
         2018                 0.467783                 0.260832
         2019                 0.666075                 0.280238
         2020                 0.646255                 0.272585
...                                ...                      ...
175      2018                 0.825402                 0.523890
         2019                 1.142284                 0.648880
         2020                 1.146163                 0.601754
         2021                 1.139400                 0.709725
         2022                 1.222811                 1.001809

               surface_pressure      NDVI  NDVI_binary  \
COUNTYFP year
1        2016      98669.413763       NaN          NaN
         2017      98590.452998       NaN          NaN
         2018      98703.732676  0.575101     0.224237
         2019      98616.818723  0.544303     0.607221
         2020      98662.765119  0.613992     0.582429
...                         ...       ...          ...
175      2018      98615.631878  0.448340     0.190099
         2019      98513.707070  0.430871     0.500662
         2020      98500.894004  0.444577     0.540486
         2021      98504.492176  0.363367     0.502115
         2022      98508.178635  0.470055     0.562357

               leaf_area_index_high_vegetation  leaf_area_index_low_vegetation
COUNTYFP year
1        2016                         2.640520                        1.977129
         2017                         2.640291                        1.977122
         2018                         2.640291                        1.977122
         2019                         2.640291                        1.977122
         2020                         2.640520                        1.977129
...                                        ...                             ...
175      2018                         0.838677                        1.182058
         2019                         0.838677                        1.182058
         2020                         0.838678                        1.182204
         2021                         0.838677                        1.182058
         2022                         0.838677                        1.182058

[616 rows x 36 columns]

In [26]:
depression_prev.head(1)

        year  depression_prevalence
CBSAFP
10420   2016               0.071575

In [27]:
cw.head(1)

   cbsacode  COUNTYFP
0     33860         1

In [28]:
depression_prev = pd.merge(depression_prev, cw, left_index=True, right_on='cbsacode').set_index(['COUNTYFP', 'year'])
depression_prev

               depression_prevalence  cbsacode
COUNTYFP year
133      2016               0.071575     10420
153      2016               0.071575     10420
133      2019               0.073754     10420
153      2019               0.073754     10420
133      2020               0.066346     10420
...                              ...       ...
155      2021               0.067161     49660
99       2019               0.062402     49660
155      2019               0.062402     49660
99       2020               0.061562     49660
155      2020               0.061562     49660

[347 rows x 2 columns]

In [29]:
pd.merge(depression_prev, yearly_tvdf, left_index=True, right_index=True)

,,depression_prevalence,cbsacode,surface_latent_heat_flux_sum,surface_net_solar_radiation_sum,surface_solar_radiation_downwards_sum,surface_thermal_radiation_downwards_sum,evaporation_from_bare_soil_sum,evaporation_from_the_top_of_canopy_sum,evaporation_from_open_water_surfaces_excluding_oceans_sum,total_evaporation_sum,...,skin_reservoir_content,volumetric_soil_water_layer_1,volumetric_soil_water_layer_3,u_component_of_wind_10m,v_component_of_wind_10m,surface_pressure,NDVI,NDVI_binary,leaf_area_index_high_vegetation,leaf_area_index_low_vegetation
COUNTYFP,year,,,,,,,,,,,,,,,,,,,,,
133,2016,0.071575,10420,-2.012176e+09,4.437461e+09,5.364411e+09,9.973388e+09,-0.502401,-0.148809,-0.103181,-0.802377,...,0.000067,0.354842,0.342893,0.827910,0.371541,97783.394833,NaN,NaN,2.117279,0.566468
153,2016,0.071575,10420,-1.886075e+09,4.481773e+09,5.391027e+09,9.981938e+09,-0.476712,-0.125075,-0.112834,-0.751944,...,0.000060,0.359475,0.349606,0.841751,0.400602,98004.150052,NaN,NaN,1.742956,0.972463
133,2019,0.073754,10420,-2.010687e+09,4.165539e+09,5.063390e+09,9.984102e+09,-0.495552,-0.165635,-0.093572,-0.801553,...,0.000081,0.374857,0.368604,0.802892,0.389309,97747.034078,0.639212,0.526838,2.116991,0.566467
153,2019,0.073754,10420,-1.839102e+09,4.216309e+09,5.092195e+09,9.991978e+09,-0.456426,-0.138371,-0.103109,-0.733163,...,0.000072,0.375245,0.367817,0.829003,0.409672,97966.666893,0.614243,0.551027,1.742673,0.972459
133,2020,0.066346,10420,-1.984455e+09,4.311112e+09,5.217801e+09,1.001057e+10,-0.493680,-0.146713,-0.101630,-0.791134,...,0.000067,0.355128,0.338903,0.842966,0.357713,97749.252679,0.573946,0.775236,2.117279,0.566468
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,2021,0.067161,49660,-2.083679e+09,4.239438e+09,5.137344e+09,1.000210e+10,-0.531741,-0.159476,-0.091907,-0.830318,...,0.000102,0.371078,0.373562,0.662121,0.349268,98018.592210,0.536219,0.507979,2.331077,0.961203
99,2019,0.062402,49660,-1.886599e+09,4.171149e+09,5.056026e+09,9.979694e+09,-0.476863,-0.148777,-0.088396,-0.752255,...,0.000086,0.380590,0.379150,0.696398,0.378584,97709.093119,0.636404,0.487567,1.993403,0.639077
155,2019,0.062402,49660,-2.026852e+09,4.125061e+09,5.003643e+09,9.947616e+09,-0.503089,-0.171819,-0.087694,-0.807928,...,0.000095,0.377250,0.373153,0.632583,0.372305,98014.555078,0.668156,0.489370,2.331077,0.961203
99,2020,0.061562,49660,-1.877961e+09,4.269089e+09,5.148546e+09,1.001691e+10,-0.486564,-0.124197,-0.098036,-0.748937,...,0.000067,0.360346,0.346997,0.761291,0.360385,97706.580648,0.539498,0.618626,1.993683,0.639078
155,2020,0.061562,49660,-2.012460e+09,4.288350e+09,5.179634e+09,9.976277e+09,-0.511941,-0.143227,-0.097470,-0.802172,...,0.000078,0.353902,0.341407,0.699004,0.342875,98006.110408,0.535302,0.633322,2.331358,0.961203