In [157]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [158]:
import pandas as pd
from src.data.loaders import *
from src.data.merge import *
from src.data.targets import create_target

In [159]:
# Load datasets
aq = load_airquality()
cl = load_climate()
gr = load_greenery()
lc = load_landcover()
sdi = load_sdi()
icd3 = load_icd(3)
cw = load_fips_crosswalk()
dfs = [aq, cl, gr, lc, sdi]

In [160]:
# Add COUNTYFP to ICD3
cbsa_county_mapping = cbsa_to_counties(cw)
icd3_expanded = expand_cbsa_to_county(icd3, cbsa_county_mapping)
dfs.append(icd3_expanded)

In [161]:
# Set indices
for df in dfs:
    set_index(df)

In [162]:
# Split into time-varying and static datasets
time_varying_dfs = [aq, cl, gr]
static_dfs = [lc, sdi]

time_varying_df = merge_datasets(time_varying_dfs)
static_df = merge_datasets(static_dfs)

Merging datasets: 100%|██████████| 2/2 [00:00<00:00, 361.55it/s]
Merging datasets: 100%|██████████| 1/1 [00:00<00:00, 1630.76it/s]

In [163]:
# Aggregate time-varying data to annual level
annual_tvdf = monthly_to_annual(time_varying_df)

In [164]:
# Cretate target variable
target = create_target(icd3_expanded)

In [165]:
annual_tvdf.merge(target, left_index=True, right_index=True)

               surface_latent_heat_flux_sum  surface_net_solar_radiation_sum  \
COUNTYFP year
3        2016                 -2.025289e+09                     4.313320e+09
         2017                 -2.048438e+09                     4.247273e+09
         2018                 -2.010754e+09                     4.050662e+09
         2019                 -1.943294e+09                     4.079229e+09
         2020                 -2.006264e+09                     4.246006e+09
...                                     ...                              ...
173      2017                 -2.010988e+09                     4.237022e+09
         2018                 -1.959365e+09                     4.015153e+09
         2019                 -1.872399e+09                     4.038337e+09
         2020                 -1.965508e+09                     4.261195e+09
         2022                 -1.958910e+09                     4.288795e+09

               surface_solar_radiation_downwards_sum  \
COUNTYFP year
3        2016                           5.391195e+09
         2017                           5.288023e+09
         2018                           5.168220e+09
         2019                           5.159034e+09
         2020                           5.318185e+09
...                                              ...
173      2017                           5.291245e+09
         2018                           5.155211e+09
         2019                           5.090801e+09
         2020                           5.362652e+09
         2022                           5.456615e+09

               surface_thermal_radiation_downwards_sum  \
COUNTYFP year
3        2016                             1.006522e+10
         2017                             1.002664e+10
         2018                             1.006962e+10
         2019                             1.004494e+10
         2020                             1.006867e+10
...                                                ...
173      2017                             9.965186e+09
         2018                             1.001304e+10
         2019                             9.995021e+09
         2020                             1.000890e+10
         2022                             9.827199e+09

               evaporation_from_bare_soil_sum  \
COUNTYFP year
3        2016                       -0.569907
         2017                       -0.575449
         2018                       -0.551929
         2019                       -0.540473
         2020                       -0.560555
...                                       ...
173      2017                       -0.568795
         2018                       -0.540591
         2019                       -0.516678
         2020                       -0.553661
         2022                       -0.548976

               evaporation_from_the_top_of_canopy_sum  \
COUNTYFP year
3        2016                               -0.100600
         2017                               -0.109968
         2018                               -0.123026
         2019                               -0.107825
         2020                               -0.101726
...                                               ...
173      2017                               -0.108699
         2018                               -0.118526
         2019                               -0.110666
         2020                               -0.096999
         2022                               -0.092429

               evaporation_from_open_water_surfaces_excluding_oceans_sum  \
COUNTYFP year
3        2016                                          -0.116706
         2017                                          -0.118438
         2018                                          -0.103479
         2019                                          -0.109161
         2020                                          -0.118420
...                                                          ...
173      2017                                          -0.106080
         2018                                          -0.092994
         2019                                          -0.095888
         2020                                          -0.105058
         2022                                          -0.104037

               total_evaporation_sum  total_precipitation_sum  \
COUNTYFP year
3        2016              -0.807733                 0.998478
         2017              -0.817859                 1.137885
         2018              -0.801541                 1.324361
         2019              -0.775264                 1.155015
         2020              -0.800277                 1.025665
...                              ...                      ...
173      2017              -0.802784                 1.176415
         2018              -0.780725                 1.282445
         2019              -0.746676                 1.085568
         2020              -0.783497                 0.966032
         2022              -0.779969                 0.874170

               surface_runoff_sum  ...  volumetric_soil_water_layer_1  \
COUNTYFP year                      ...
3        2016            0.037323  ...                       0.333016
         2017            0.062347  ...                       0.343546
         2018            0.081635  ...                       0.363887
         2019            0.076111  ...                       0.344839
         2020            0.042206  ...                       0.330758
...                           ...  ...                            ...
173      2017            0.072308  ...                       0.334270
         2018            0.069650  ...                       0.354282
         2019            0.053206  ...                       0.335296
         2020            0.034692  ...                       0.317308
         2022            0.038793  ...                       0.305242

               volumetric_soil_water_layer_3  u_component_of_wind_10m  \
COUNTYFP year
3        2016                       0.314133                 1.169959
         2017                       0.336058                 1.287091
         2018                       0.361184                 0.796536
         2019                       0.334407                 1.141891
         2020                       0.310920                 1.122855
...                                      ...                      ...
173      2017                       0.325671                 1.297929
         2018                       0.350273                 0.797551
         2019                       0.324829                 1.089735
         2020                       0.298127                 1.167241
         2022                       0.293188                 1.293035

               v_component_of_wind_10m  surface_pressure      NDVI  \
COUNTYFP year
3        2016                 0.690497      98582.639698       NaN
         2017                 0.751189      98496.203278       NaN
         2018                 0.509872      98641.087073  0.541527
         2019                 0.621230      98540.380976  0.400690
         2020                 0.574892      98563.793765  0.461946
...                                ...               ...       ...
173      2017                 0.633081      99154.905946       NaN
         2018                 0.386729      99315.367230  0.423789
         2019                 0.468340      99207.119512  0.343362
         2020                 0.466086      99225.346869  0.399681
         2022                 0.824609      99228.341083  0.365286

               NDVI_binary  leaf_area_index_high_vegetation  \
COUNTYFP year
3        2016          NaN                         1.660775
         2017          NaN                         1.660762
         2018     0.377489                         1.660762
         2019     0.555740                         1.660762
         2020     0.537696                         1.660775
...                    ...                              ...
173      2017          NaN                         2.333068
         2018     0.283812                         2.333068
         2019     0.503930                         2.333068
         2020     0.531279                         2.333075
         2022     0.517716                         2.333068

               leaf_area_index_low_vegetation  depr_prev
COUNTYFP year
3        2016                        1.417706   0.064020
         2017                        1.417541   0.059163
         2018                        1.417541   0.064933
         2019                        1.417541   0.063858
         2020                        1.417706   0.067798
...                                       ...        ...
173      2017                        1.214545   0.064112
         2018                        1.214545   0.067128
         2019                        1.214545   0.069102
         2020                        1.214707   0.066154
         2022                        1.214545   0.072687

[333 rows x 37 columns]

In [168]:
from src.config import PROCESSED_DATA_DIR
df = pd.read_csv(PROCESSED_DATA_DIR / "dataset.csv")

df

,COUNTYFP,year,surface_latent_heat_flux_sum,surface_net_solar_radiation_sum,surface_solar_radiation_downwards_sum,surface_thermal_radiation_downwards_sum,evaporation_from_bare_soil_sum,evaporation_from_the_top_of_canopy_sum,evaporation_from_open_water_surfaces_excluding_oceans_sum,total_evaporation_sum,...,HHCrowding_score,Nonemployed_score,sdi,pct_Poverty_LT100,pct_Single_Parent_Fam,pct_Education_LT12years,pct_NonEmployed,pctHH_No_Vehicle,pctHH_Renter_Occupied,pctHH_Crowding
0,3,2016,-2.025289e+09,4.313320e+09,5.391195e+09,1.006522e+10,-0.569907,-0.100600,-0.116706,-0.807733,...,7,52,-0.061643,0.139258,0.179940,0.096970,0.372661,0.080394,0.329323,0.010603
1,3,2017,-2.048438e+09,4.247273e+09,5.288023e+09,1.002664e+10,-0.575449,-0.109968,-0.118438,-0.817859,...,7,52,-0.061643,0.139258,0.179940,0.096970,0.372661,0.080394,0.329323,0.010603
2,3,2018,-2.010754e+09,4.050662e+09,5.168220e+09,1.006962e+10,-0.551929,-0.123026,-0.103479,-0.801541,...,7,52,-0.061643,0.139258,0.179940,0.096970,0.372661,0.080394,0.329323,0.010603
3,3,2019,-1.943294e+09,4.079229e+09,5.159034e+09,1.004494e+10,-0.540473,-0.107825,-0.109161,-0.775264,...,7,52,-0.061643,0.139258,0.179940,0.096970,0.372661,0.080394,0.329323,0.010603
4,3,2020,-2.006264e+09,4.246006e+09,5.318185e+09,1.006867e+10,-0.560555,-0.101726,-0.118420,-0.800277,...,7,52,-0.061643,0.139258,0.179940,0.096970,0.372661,0.080394,0.329323,0.010603
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
328,173,2017,-2.010988e+09,4.237022e+09,5.291245e+09,9.965186e+09,-0.568795,-0.108699,-0.106080,-0.802784,...,1,14,-0.828912,0.129215,0.116886,0.056782,0.292019,0.046077,0.347447,0.005060
329,173,2018,-1.959365e+09,4.015153e+09,5.155211e+09,1.001304e+10,-0.540591,-0.118526,-0.092994,-0.780725,...,1,14,-0.828912,0.129215,0.116886,0.056782,0.292019,0.046077,0.347447,0.005060
330,173,2019,-1.872399e+09,4.038337e+09,5.090801e+09,9.995021e+09,-0.516678,-0.110666,-0.095888,-0.746676,...,1,14,-0.828912,0.129215,0.116886,0.056782,0.292019,0.046077,0.347447,0.005060
331,173,2020,-1.965508e+09,4.261195e+09,5.362652e+09,1.000890e+10,-0.553661,-0.096999,-0.105058,-0.783497,...,1,14,-0.828912,0.129215,0.116886,0.056782,0.292019,0.046077,0.347447,0.005060
332,173,2022,-1.958910e+09,4.288795e+09,5.456615e+09,9.827199e+09,-0.548976,-0.092429,-0.104037,-0.779969,...,1,14,-0.828912,0.129215,0.116886,0.056782,0.292019,0.046077,0.347447,0.005060